name: build-env
channels:
- defaults
- conda-forge
dependencies:
  - numpy>=1.11.0
  - pyyaml>=3.12
  - cerberus>=1.0.0
  - pint>=0.7.2
  - pandas
  - uncertainties
  - habanero>=0.6.0
  - orcid
  - sphinx
  - nbsphinx
  - ipython
  - conda-build
  - anaconda-client
  - doctr
